### ISSUE TITLE
Example of Settings.StyleCop file

### ISSUE THREAD

**Issue by IvanRibakov** [bbadjari/stylecopcli#5]
I've never used StyleCop (in any of it's versions/integrations) or StyleCopCLI. Where can I find list of parameters that can be configured in the settings file and their format?

**Comment by bbadjari** [comment]
You should download StyleCop 4.7 or above, depending on the version of Visual Studio you are using. This will provide an extension for Visual Studio as well as an editor for creating and editing the StyleCop settings file. This file has an XML format containing the rules to enforce and can be generated either through Visual Studio or through the StyleCop editor.

Please note that more recent versions of Visual Studio would benefit from the [StyleCop Analyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) project as this will support recent versions of C# because it makes use of [Roslyn](https://github.com/dotnet/roslyn) for code analysis.
